# Welcome to Jekyll! The static website generator.

title: Yigal Duppen
email: 
description: Yigal Duppen is a driven software architect
baseurl: "" 
url: "" 
twitter_username: 
github_username:  

google_analytics: 

# Build settings
markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data", "fenced_code_blocks", "underline", "highlight", "quote", "superscript", "smart"]

exclude: [
README.md,
Gemfile,
Gemfile.lock
]

gems:
  - octopress-autoprefixer
  - jekyll-sitemap

collections:
  projects:
    output: true
    # permalink: projects/:path/
  writings:
    output: true
    # permalink: writings/:path/



