web:
  name: web development
  color: oranje

service:
  name: service development
  color: blauw

java:
  name: java development
  color: groen

go:
  name: go development
  color: ossen

python:
  name: python development
  color: bruin

game:
  name: game development
  color: limoen

consultancy:
  name: consultancy
  color: fuchsia

devops:
  name: devops
  color: oceaan

research:
  name: research
  color: bruin

fun:
  name: fun
  color: ossen


